### ISSUE TITLE
Death in multiplayer causes crash

### ISSUE THREAD

**Issue by ammoore00** [BTW-Community/BTW-Public#100]
Crash log:
https://hastebin.com/uzogajakim.lua

**Comment by ammoore00** [comment]
Confirmed again by Kyblie on discord, same error message:

```
java.lang.NullPointerException
	at rh.SetEntityItemAsDroppedOnPlayerDeath(EntityItem.java:755)
	at sq.a(EntityPlayer.java:739)
	at so.m(InventoryPlayer.java:744)
	at sq.a(EntityPlayer.java:652)
	at ng.a(EntityLiving.java:2490)
	at sq.a(EntityPlayer.java:454)
	at bdk.a(NetClientHandler.java:903)
	at dn.a(SourceFile:31)
	at ci.b(SourceFile:350)
	at bdk.d(NetClientHandler.java:100)
	at bds.b(WorldClient.java:70)
	at net.minecraft.client.Minecraft.l(Minecraft.java:1878)
	at net.minecraft.client.Minecraft.K(Minecraft.java:850)
	at net.minecraft.client.Minecraft.run(Minecraft.java:773)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Hirachosan** [comment]
`Caused by: java.lang.NullPointerException: Cannot read field "worldServers" because the return value of "net.minecraft.server.MinecraftServer.getServer()" is null`
in `EntityItem.SetEntityItemAsDroppedOnPlayerDeath( EntityPlayer player )`

**Comment by Hirachosan** [comment]
I ran some test on an old build, and it doesn't seem to call this method clientside on old  methods, while it does in the newer versions

**Comment by Hirachosan** [comment]
Found the difference to be in EntityPlayerMP. An added line has `EntityLivingOnDeath(par1DamageSource);` while older versions don't. disabling this stops the crash from happening

**Comment by Hirachosan** [comment]
not sure what it's used for, potential (tested it) solution: put `if (world.isRemote )` around it?

**Comment by ammoore00** [comment]
Fixed for next release. Thanks Hiracho :)
