### ISSUE TITLE
Server errors on stopping and starting

### ISSUE THREAD

**Issue by Kubimate** [BTW-Community/BTW-Public#112]
Server starts for the first time and generates new world, no errors
```
228 recipes
27 achievements
2021-10-28 12:09:25 [INFO] Starting minecraft server version 1.5.2
2021-10-28 12:09:25 [INFO] Loading properties
2021-10-28 12:09:25 [INFO] Default game type: SURVIVAL
2021-10-28 12:09:25 [INFO] Generating keypair
2021-10-28 12:09:25 [INFO] Starting Minecraft server on xxxx
2021-10-28 12:09:26 [INFO] Preparing level "world"
...Add-On Handler Initializing...
2021-10-28 12:09:26 [INFO] ...Add-On Handler Initializing...
Better Than Wolves Community Edition Version 1.2.1 Initializing...
2021-10-28 12:09:26 [INFO] Better Than Wolves Community Edition Version 1.2.1 In
itializing...
Better Than Wolves Initialization Complete.
2021-10-28 12:09:26 [INFO] Better Than Wolves Initialization Complete.
...Add-On Handler Loading Custom Language File With Prefix: BTW...
2021-10-28 12:09:26 [INFO] ...Add-On Handler Loading Custom Language File With P
refix: BTW...
...Add-On Handler Initialization Complete...
2021-10-28 12:09:26 [INFO] ...Add-On Handler Initialization Complete...
2021-10-28 12:09:26 [INFO] Preparing start region for level 0
2021-10-28 12:09:27 [INFO] Preparing spawn area: 11%
2021-10-28 12:09:28 [INFO] Preparing spawn area: 25%
2021-10-28 12:09:29 [INFO] Preparing spawn area: 42%
2021-10-28 12:09:30 [INFO] Preparing spawn area: 56%
2021-10-28 12:09:31 [INFO] Preparing spawn area: 68%
2021-10-28 12:09:32 [INFO] Preparing spawn area: 79%
2021-10-28 12:09:33 [INFO] Preparing spawn area: 92%
2021-10-28 12:09:34 [INFO] Done (8,169s)! For help, type "help" or "?"
```
Server stops for the first time nad gives error
```
stop
2021-10-28 12:12:19 [INFO] Stopping the server
2021-10-28 12:12:19 [INFO] Stopping server
2021-10-28 12:12:19 [INFO] Saving players
java.net.SocketException: Socket closed
        at java.base/sun.nio.ch.NioSocketImpl.endAccept(NioSocketImpl.java:689)
        at java.base/sun.nio.ch.NioSocketImpl.accept(NioSocketImpl.java:762)
        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:681)
        at java.base/java.net.ServerSocket.platformImplAccept(ServerSocket.java:
647)
        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:623)
        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:580)
        at java.base/java.net.ServerSocket.accept(ServerSocket.java:538)
        at if.run(SourceFile:61)
2021-10-28 12:12:19 [INFO] Saving worlds
2021-10-28 12:12:19 [INFO] Closing listening thread
2021-10-28 12:12:19 [INFO] Saving chunks for level 'world'/Overworld
2021-10-28 12:12:19 [INFO] Saving chunks for level 'world'/Nether
2021-10-28 12:12:19 [INFO] Saving chunks for level 'world'/The End
2021-10-28 12:12:19 [INFO] Stopping server
```
Server starts again and gives errors (this happens every time from now on)
```
228 recipes
27 achievements
2021-10-28 12:13:41 [INFO] Starting minecraft server version 1.5.2
2021-10-28 12:13:41 [INFO] Loading properties
2021-10-28 12:13:41 [INFO] Default game type: SURVIVAL
2021-10-28 12:13:41 [INFO] Generating keypair
2021-10-28 12:13:41 [INFO] Starting Minecraft server on xxxx
2021-10-28 12:13:41 [INFO] Preparing level "world"
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because
 "FCAddOnHandler.addonWorldDataMap" is null
        at ajv.LoadModInfoFromNBT(WorldInfo.java:711)
        at ajv.<init>(WorldInfo.java:173)
        at aju.c(SourceFile:56)
        at ajq.b(SourceFile:100)
        at net.minecraft.server.MinecraftServer.b(SourceFile:109)
        at net.minecraft.server.MinecraftServer.a(SourceFile:146)
        at hz.c(SourceFile:177)
        at net.minecraft.server.MinecraftServer.run(SourceFile:306)
        at gp.run(SourceFile:573)
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because
 "FCAddOnHandler.addonWorldDataMap" is null
        at ajv.LoadModInfoFromNBT(WorldInfo.java:711)
        at ajv.<init>(WorldInfo.java:173)
        at aju.c(SourceFile:67)
        at ajq.b(SourceFile:100)
        at net.minecraft.server.MinecraftServer.b(SourceFile:109)
        at net.minecraft.server.MinecraftServer.a(SourceFile:146)
        at hz.c(SourceFile:177)
        at net.minecraft.server.MinecraftServer.run(SourceFile:306)
        at gp.run(SourceFile:573)
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because
 "FCAddOnHandler.addonWorldDataMap" is null
        at ajv.LoadModInfoFromNBT(WorldInfo.java:711)
        at ajv.<init>(WorldInfo.java:173)
        at ajt.d(SaveHandler.java:130)
        at net.minecraft.server.MinecraftServer.a(SourceFile:155)
        at hz.c(SourceFile:177)
        at net.minecraft.server.MinecraftServer.run(SourceFile:306)
        at gp.run(SourceFile:573)
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because
 "FCAddOnHandler.addonWorldDataMap" is null
        at ajv.LoadModInfoFromNBT(WorldInfo.java:711)
        at ajv.<init>(WorldInfo.java:173)
        at ajt.d(SaveHandler.java:146)
        at net.minecraft.server.MinecraftServer.a(SourceFile:155)
        at hz.c(SourceFile:177)
        at net.minecraft.server.MinecraftServer.run(SourceFile:306)
        at gp.run(SourceFile:573)
...Add-On Handler Initializing...
2021-10-28 12:13:41 [INFO] ...Add-On Handler Initializing...
Better Than Wolves Community Edition Version 1.2.1 Initializing...
2021-10-28 12:13:41 [INFO] Better Than Wolves Community Edition Version 1.2.1 In
itializing...
Better Than Wolves Initialization Complete.
2021-10-28 12:13:42 [INFO] Better Than Wolves Initialization Complete.
...Add-On Handler Loading Custom Language File With Prefix: BTW...
2021-10-28 12:13:42 [INFO] ...Add-On Handler Loading Custom Language File With P
refix: BTW...
...Add-On Handler Initialization Complete...
2021-10-28 12:13:42 [INFO] ...Add-On Handler Initialization Complete...
2021-10-28 12:13:42 [INFO] Preparing start region for level 0
2021-10-28 12:13:42 [INFO] Done (1,098s)! For help, type "help" or "?"
```
Server stops and gives same error as before
Is it something *not to worry about*™ or not to worry about?

**Comment by ammoore00** [comment]
Fixed for next release
