### ISSUE TITLE
Confirm attribute values for BTW edits

### ISSUE THREAD

**Issue by ammoore00** [BTW-Community/BTW-Public#252]
Crash occurred, presumably when an ocelot attacked a chicken. BTW edits to classes may not include attribute assignments.

`java.lang.NullPointerException: Cannot invoke "net.minecraft.src.AttributeInstance.getAttributeValue()" because the return value of "net.minecraft.src.EntityLiving.getEntityAttribute(net.minecraft.src.Attribute)" is null
	at net.minecraft.src.EntityLiving.meleeAttack(EntityLiving.java:244)
	at btw.entity.mob.OcelotEntity.attackEntityAsMob(OcelotEntity.java:178)
	at net.minecraft.src.EntityAIOcelotAttack.updateTask(EntityAIOcelotAttack.java:79)
	at net.minecraft.src.EntityAITasks.onUpdateTasks(EntityAITasks.java:122)
	at net.minecraft.src.EntityLiving.entityLivingUpdateAITasks(EntityLiving.java:1056)
	at net.minecraft.src.EntityLiving.updateAITasks(EntityLiving.java:1036)
	at net.minecraft.src.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2124)
	at net.minecraft.src.EntityLiving.entityLivingOnLivingUpdate(EntityLiving.java:875)
	at net.minecraft.src.EntityLiving.onLivingUpdate(EntityLiving.java:867)
	at net.minecraft.src.EntityAgeable.onLivingUpdate(EntityAgeable.java:154)
	at net.minecraft.src.EntityAnimal.onLivingUpdate(EntityAnimal.java:57)
	at net.minecraft.src.EntityLivingBase.onUpdate(EntityLivingBase.java:1957)
	at net.minecraft.src.EntityLiving.onUpdate(EntityLiving.java:693)
	at net.minecraft.src.World.updateEntityWithOptionalForce(World.java:2077)
	at net.minecraft.src.WorldServer.updateEntityWithOptionalForce(WorldServer.java:744)
	at net.minecraft.src.World.updateEntity(World.java:2044)
	at net.minecraft.src.World.updateEntities(World.java:1909)
	at net.minecraft.src.WorldServer.updateEntities(WorldServer.java:558)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:716)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:639)
	at net.minecraft.src.IntegratedServer.tick(IntegratedServer.java:130)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:528)
	at net.minecraft.src.ThreadMinecraftServer.run(ThreadMinecraftServer.java:18)`

**Comment by Arminias** [comment]
Checked and added a quite couple of these cases now. But maybe still a few left somewhere
