### ISSUE TITLE
Bug: Players get an NPE on server when another player logs in

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#77]
From Kubimate on Discord:
> Hey me and my friend cannot be on my server at the same time. If one is logged, and the other logs in we are both disconected and our games crashes, we are on 1.1.1, same thing on 1.1.0

```
Description: Exception in world tick

java.lang.NullPointerException
    at mv.getRegisteredReplacement(EntityList.java:483)
    at mv.createEntityOfType(EntityList.java:438)
    at bdk.a(NetClientHandler.java:457)
    at cs.a(SourceFile:68)
    at ci.b(SourceFile:350)
    at bdk.d(NetClientHandler.java:100)
    at bds.b(WorldClient.java:70)
    at net.minecraft.client.Minecraft.l(Minecraft.java:1878)
    at net.minecraft.client.Minecraft.K(Minecraft.java:850)
    at net.minecraft.client.Minecraft.run(Minecraft.java:773)
    at java.lang.Thread.run(Unknown Source)
```
https://hastebin.com/fehixihizi.lua

**Comment by ammoore00** [comment]
Fixed for v1.1.2
